apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ebank-api-deploy
  name: ebank-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebank-api-pod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ebank-api-pod
    spec:
      containers:
      - image: ebank-api
        name: ebank-api-container
        imagePullPolicy: Never
        ports:
          - name: liveness-port
            containerPort: 8080
        volumeMounts:
          - mountPath: /logs/
            name: logs-volume
        resources: {}
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: liveness-port
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ebanking/version
            port: liveness-port
          initialDelaySeconds: 5
          failureThreshold: 3
          periodSeconds: 15
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: ebank-api-pvc
status: {}
