apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ebank-api-deploy
  name: ebank-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebank-api-pod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ebank-api-pod
    spec:
#      securityContext:
#        runAsUser: 1000
#        runAsGroup: 3000
#        fsGroup: 2000
      containers:
      - image: ebank-api
        name: ebank-api-container
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: /logs/
            name: logs-volume
        resources: {}
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: ebanking-api-pvc
status: {}
