apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebank-api-pvc
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeName: ebank-api-pv