apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebank-api-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/ebank-api
