apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebanking-api-pvc
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeName: ebanking-api-pv