apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ebank-api-deploy
  name: ebank-api-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ebank-api-pod
  type: NodePort
status:
  loadBalancer: {}
